dist: trusty
sudo: required
language: python
python:
  - "3.5"

# command to install dependencies
install:
  - sudo apt-get install -y python-dev libxml2-dev libxslt1-dev python3-dev
  - pip install pytest-cov codecov codacy-coverage
  - pip install -e .

# command to run tests
script:
  - pytest --cov=validation ./tests/

after_success:
  - coverage xml
  - codecov
  - python-codacy-coverage -r coverage.xml
