FROM python:3.6-stretch

LABEL maintainer="carl.wilson@openpreservation.org" \
      org.openpreservation.vendor="Open Preservation Foundation" \
      version="0.1"

WORKDIR /tmp

COPY setup.py setup.py
COPY requirements.txt requirements.txt
COPY ip_validation/* ip_validation/
COPY README.md README.md
RUN pip install -U pip && pip install -r /tmp/requirements.txt && pip install -U .[flask]

EXPOSE 5000
WORKDIR /app
ENV FLASK_APP='ip_validation'
ENTRYPOINT pip install -Ue . && flask run --host "0.0.0.0" --port "5000"
