# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eark_ip.model.base_model_ import Model
from eark_ip import util


class IpBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sha1: str=None, ip_file: str=None):  # noqa: E501
        """IpBody - a model defined in Swagger

        :param sha1: The sha1 of this IpBody.  # noqa: E501
        :type sha1: str
        :param ip_file: The ip_file of this IpBody.  # noqa: E501
        :type ip_file: str
        """
        self.swagger_types = {
            'sha1': str,
            'ip_file': str
        }

        self.attribute_map = {
            'sha1': 'sha1',
            'ip_file': 'ip_file'
        }
        self._sha1 = sha1
        self._ip_file = ip_file

    @classmethod
    def from_dict(cls, dikt) -> 'IpBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ipBody of this IpBody.  # noqa: E501
        :rtype: IpBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sha1(self) -> str:
        """Gets the sha1 of this IpBody.


        :return: The sha1 of this IpBody.
        :rtype: str
        """
        return self._sha1

    @sha1.setter
    def sha1(self, sha1: str):
        """Sets the sha1 of this IpBody.


        :param sha1: The sha1 of this IpBody.
        :type sha1: str
        """

        self._sha1 = sha1

    @property
    def ip_file(self) -> str:
        """Gets the ip_file of this IpBody.


        :return: The ip_file of this IpBody.
        :rtype: str
        """
        return self._ip_file

    @ip_file.setter
    def ip_file(self, ip_file: str):
        """Sets the ip_file of this IpBody.


        :param ip_file: The ip_file of this IpBody.
        :type ip_file: str
        """

        self._ip_file = ip_file
