# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eark_ip.model.base_model_ import Model
from eark_ip.model.checksum import Checksum  # noqa: F401,E501
from eark_ip import util


class ManifestEntry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, path: str=None, size: int=0, checksums: List[Checksum]=None):  # noqa: E501
        """ManifestEntry - a model defined in Swagger

        :param path: The path of this ManifestEntry.  # noqa: E501
        :type path: str
        :param size: The size of this ManifestEntry.  # noqa: E501
        :type size: int
        :param checksums: The checksums of this ManifestEntry.  # noqa: E501
        :type checksums: List[Checksum]
        """
        self.swagger_types = {
            'path': str,
            'size': int,
            'checksums': List[Checksum]
        }

        self.attribute_map = {
            'path': 'path',
            'size': 'size',
            'checksums': 'checksums'
        }
        self._path = path
        self._size = size
        self._checksums = checksums

    @classmethod
    def from_dict(cls, dikt) -> 'ManifestEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The manifestEntry of this ManifestEntry.  # noqa: E501
        :rtype: ManifestEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> str:
        """Gets the path of this ManifestEntry.


        :return: The path of this ManifestEntry.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this ManifestEntry.


        :param path: The path of this ManifestEntry.
        :type path: str
        """

        self._path = path

    @property
    def size(self) -> int:
        """Gets the size of this ManifestEntry.


        :return: The size of this ManifestEntry.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this ManifestEntry.


        :param size: The size of this ManifestEntry.
        :type size: int
        """

        self._size = size

    @property
    def checksums(self) -> List[Checksum]:
        """Gets the checksums of this ManifestEntry.


        :return: The checksums of this ManifestEntry.
        :rtype: List[Checksum]
        """
        return self._checksums

    @checksums.setter
    def checksums(self, checksums: List[Checksum]):
        """Sets the checksums of this ManifestEntry.


        :param checksums: The checksums of this ManifestEntry.
        :type checksums: List[Checksum]
        """

        self._checksums = checksums
