# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eark_ip.model.base_model_ import Model
from eark_ip.model.checksum import Checksum  # noqa: F401,E501
from eark_ip import util


class PackageDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, checksums: List[Checksum]=None):  # noqa: E501
        """PackageDetails - a model defined in Swagger

        :param name: The name of this PackageDetails.  # noqa: E501
        :type name: str
        :param checksums: The checksums of this PackageDetails.  # noqa: E501
        :type checksums: List[Checksum]
        """
        self.swagger_types = {
            'name': str,
            'checksums': List[Checksum]
        }

        self.attribute_map = {
            'name': 'name',
            'checksums': 'checksums'
        }
        self._name = name
        self._checksums = checksums

    @classmethod
    def from_dict(cls, dikt) -> 'PackageDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The packageDetails of this PackageDetails.  # noqa: E501
        :rtype: PackageDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this PackageDetails.


        :return: The name of this PackageDetails.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PackageDetails.


        :param name: The name of this PackageDetails.
        :type name: str
        """

        self._name = name

    @property
    def checksums(self) -> List[Checksum]:
        """Gets the checksums of this PackageDetails.


        :return: The checksums of this PackageDetails.
        :rtype: List[Checksum]
        """
        return self._checksums

    @checksums.setter
    def checksums(self, checksums: List[Checksum]):
        """Sets the checksums of this PackageDetails.


        :param checksums: The checksums of this PackageDetails.
        :type checksums: List[Checksum]
        """

        self._checksums = checksums
