# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eark_ip.model.base_model_ import Model
from eark_ip.model.package_details import PackageDetails  # noqa: F401,E501
from eark_ip.model.package_state import PackageState  # noqa: F401,E501
from eark_ip import util


class Upload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uid: str=None, state: PackageState=None, details: PackageDetails=None):  # noqa: E501
        """Upload - a model defined in Swagger

        :param uid: The uid of this Upload.  # noqa: E501
        :type uid: str
        :param state: The state of this Upload.  # noqa: E501
        :type state: PackageState
        :param details: The details of this Upload.  # noqa: E501
        :type details: PackageDetails
        """
        self.swagger_types = {
            'uid': str,
            'state': PackageState,
            'details': PackageDetails
        }

        self.attribute_map = {
            'uid': 'uid',
            'state': 'state',
            'details': 'details'
        }
        self._uid = uid
        self._state = state
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'Upload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The upload of this Upload.  # noqa: E501
        :rtype: Upload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> str:
        """Gets the uid of this Upload.


        :return: The uid of this Upload.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid: str):
        """Sets the uid of this Upload.


        :param uid: The uid of this Upload.
        :type uid: str
        """

        self._uid = uid

    @property
    def state(self) -> PackageState:
        """Gets the state of this Upload.


        :return: The state of this Upload.
        :rtype: PackageState
        """
        return self._state

    @state.setter
    def state(self, state: PackageState):
        """Sets the state of this Upload.


        :param state: The state of this Upload.
        :type state: PackageState
        """

        self._state = state

    @property
    def details(self) -> PackageDetails:
        """Gets the details of this Upload.


        :return: The details of this Upload.
        :rtype: PackageDetails
        """
        return self._details

    @details.setter
    def details(self, details: PackageDetails):
        """Sets the details of this Upload.


        :param details: The details of this Upload.
        :type details: PackageDetails
        """

        self._details = details
